In [2]:
import pandas as pd
import sqlite3

In [13]:
# Extract
df = pd.read_csv('data/data101.csv')

# Transform
df['age'] = df['age'].fillna(0)
df['salary'] = df['salary'] * 1.1

# Load
# conn = sqlite3.connect('test.db')
# df.to_sql('users', conn, if_exists='replace', index=False)

print("ETL Completed")

FileNotFoundError: [Errno 2] No such file or directory: 'data/data101.csv'

In [9]:
df

   id     name   age   salary
0   1    Alice  25.0  55000.0
1   2      Bob   0.0  66000.0
2   3  Charlie  30.0  77000.0

In [6]:
# Load
conn = sqlite3.connect('test.db')
df.to_sql('users', conn, if_exists='replace', index=False)

3

In [10]:
res = pd.read_sql('Select * from users',con=conn)

In [12]:
res

   id     name   age   salary
0   1    Alice  25.0  55000.0
1   2      Bob   0.0  66000.0
2   3  Charlie  30.0  77000.0